1. try catch finally 구문

```kotlin
fun parseIntOrThrow(str: String) : Int {
  try{
      return str.toInt()
  }catch(e: NumberFormatException) {
      throw IllegalArgumentException("주어진 ${str}은 숫자가 아닙니다.")
  }
}
```

```kotlin
fun parseIntOrThroV2(str: String) : Int? {
  return try{
      return str.toInt()
  }catch(e: NumberFormatException) {
      return null
  }
}

```

2. Checked Exception 과 unChecked Exception

- 프로젝트 내 파일의 내용물을 읽어오는 예제

```java
public void readFile() throws IOException {
  File currentFile = new File(".");
  File file = new File(currentFile.getAbsolutePath() + "/a.txt");
  BufferedReader reader = new BufferedReader(new FileReader(file));
  System.out.println(reader.readline());
  reader.close();
}

```

```kotlin
fun readFile() {
     val currentFile  = File(".")
     val file = File(currentFile.absolutePath + "/a.txt")
     val reader = BufferedReader(FileReader(file))
     println(reader.readLine())
     reader.close()
}
```
- 자바에서는 Checked Exception 인 경우, 전파되는 예외를 던져줘야하는데, 코틀린에서는 모두 unchecked Exception으로 던져주지 않아도 된다.

3. try with resources
- try 가 끝나면, 자동으로 외부 자원을 닫아주는 코드 

```java
public void readFile(String path) throws IOException {
    try (BufferedReader reader = new BufferedReader(new FileReader(path))){
        System.out.println(reader.readLine());
    }
}
```

``` kotlin
fun readFile(path: String) {
    BufferedReader(FileRedaer(path)).use {
        reader -> println(reader.readLine())
    }
}
```
- 코틀린에서는 try with resources 사용하는 것이 아닌, use 키워드를 사용한다. 

